# version は記載しない（指定どおり）

x-app-base: &app_base
  build:
    context: .
    dockerfile: Dockerfile
  working_dir: /app
  volumes:
    - ./:/app
    # 必要な場合のみコメントを外す（AWS 認証をホストから使う）
    # - ~/.aws:/root/.aws:ro
  environment:
    # 開発時は 8000 固定。App Runner ではサービス側が PORT を注入する想定。
    - PORT=8000

services:
  web:
    <<: *app_base
    container_name: fastapi_dev
    env_file:
      - .env.dev
    ports:
      - "8000:8000"
    command: >
      sh -c "uvicorn server.main:app --host 0.0.0.0 --port $${PORT} --reload"
