name: Update Parquet

on:
  push:
    branches: [main]
    paths:
      - "server/**"
      - "server.py"
      - "common_cfg/**"
      - "Dockerfile"
      - "docker-compose.yml"
      - "pipelines/**"
      - "data/parquet/**"
      - "requirements.txt"
      - "pyproject.toml"
      - "poetry.lock"
      - ".github/workflows/update-parquet.yml"
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

jobs:
  update-parquet:
    runs-on: ubuntu-latest
    environment:
      name: AWS_OIDC
    env:
      AWS_REGION: ${{ vars.AWS_REGION }}
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      DATA_BUCKET: ${{ vars.DATA_BUCKET }}
      PARQUET_PREFIX: ${{ vars.PARQUET_PREFIX }}

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run parquet pipeline
        run: |
          python -m pipelines.run_daily_pipeline --target s3
        env:
          DATA_BUCKET: ${{ env.DATA_BUCKET }}
          PARQUET_PREFIX: ${{ env.PARQUET_PREFIX }}
          AWS_REGION: ${{ env.AWS_REGION }}

      - name: Sync parquet to S3
        run: |
          aws s3 sync data/parquet "s3://${{ env.DATA_BUCKET }}/${{ env.PARQUET_PREFIX }}" --delete
