name: YFinance Smoke Test

on:
  push:
    branches:
      - yfinance-smoke
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

jobs:
  smoke:
    runs-on: ubuntu-latest
    environment: AWS_OIDC

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas pyarrow yfinance

      - name: Run yfinance smoke script
        run: python scripts/yfinance_smoke.py

      - name: Generate parquet sample via yfinance
        run: python scripts/gen_yfinance_parquet.py

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION || 'ap-northeast-1' }}

      - name: Upload sample parquet to S3
        env:
          S3_BUCKET: ${{ vars.S3_BUCKET }}
          PARQUET_PREFIX: ${{ vars.PARQUET_PREFIX }}
        run: |
          set -euo pipefail
          if [ -z "${S3_BUCKET}" ]; then
            echo "::error::S3_BUCKET (vars.S3_BUCKET) is not defined."
            exit 1
          fi
          PREFIX="${PARQUET_PREFIX:-parquet/}"
          DEST_KEY="${PREFIX%/}/smoke/yfinance-smoke-test.parquet"
          aws s3 cp \
            yfinance-smoke-test.parquet \
            "s3://${S3_BUCKET}/${DEST_KEY}" \
            --sse AES256 \
            --cache-control "max-age=60" \
            --only-show-errors
          echo "uploaded to s3://${S3_BUCKET}/${DEST_KEY}"

      - name: Upload parquet artifact
        uses: actions/upload-artifact@v4
        with:
          name: yfinance-smoke-test
          path: yfinance-smoke-test.parquet
