name: YFinance Parquet Smoke

on:
  push:
    branches:
      - yfinance-smoke
  workflow_dispatch: {}

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas pyarrow

      - name: Generate parquet
        run: python scripts/gen_yfinance_parquet.py

      - name: Upload parquet artifact
        uses: actions/upload-artifact@v4
        with:
          name: yfinance-smoke-test-parquet
          path: yfinance-smoke-test.parquet
