name: YFinance Smoke Test

on:
  push:
    branches:
      - main
      - yfinance-smoke
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

jobs:
  smoke:
    runs-on: ubuntu-latest
    environment: AWS_OIDC

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas pyarrow yfinance boto3

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION || 'ap-northeast-1' }}

      - name: Run yfinance smoke script (5 tickers)
        run: python scripts/yfinance_smoke.py

      - name: Generate parquet samples via yfinance
        run: python scripts/gen_yfinance_parquet.py

      - name: Upload parquet artifact
        uses: actions/upload-artifact@v4
        with:
          name: yfinance-smoke-test
          path: yfinance-smoke-test-*.parquet
